name: AzureLoginSample

on:
  push:
    branches:
      - azure-action-test

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"