name: Common Info

on:
  push:
    branches:
      - action-common-info
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Env Parameters
      run: |
        echo Home ${HOME}
        echo GITHUB_WORKFLOW ${GITHUB_WORKFLOW}
        echo GITHUB_ACTION ${GITHUB_ACTION}
        echo GITHUB_ACTOR ${GITHUB_ACTOR}
        echo GITHUB_REPOSITORY ${GITHUB_REPOSITORY}
        echo GITHUB_EVENT_NAME ${GITHUB_EVENT_NAME}
        echo GITHUB_EVENT_PATH ${GITHUB_EVENT_PATH}
        echo GITHUB_WORKSPACE ${GITHUB_WORKSPACE}
        echo GITHUB_SHA ${GITHUB_SHA}
        echo GITHUB_REF ${GITHUB_REF}
        echo GITHUB_HEAD_REF ${GITHUB_HEAD_REF}
        echo GITHUB_BASE_REF ${GITHUB_BASE_REF}