name: Node CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
  upload-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Upload files
        uses: actions/upload-artifact@v2
        with: 
          name: staitc-file
          path: dist/
  release-project:
    runs-on: ubuntu-latest
    needs: upload-files
    steps:
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: staitc-file
      - name: Archive files
        uses: thedoctor0/zip-release@master
        with:
          filename: helloworld.zip
      - name: Create Github release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
      - name: Upload asset to Github Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url}}
          asset_path: ./helloworld.zip
          asset_name: helloworld-v{{ github.run_number }}.zip
          asset_content_type: application/zip