name: Pull Request Test

on: 
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Unit Test
      run: |
        echo "do test"
        exit 1