name: Pull Request Test

on: 
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    - name: Unit Test
      run: |
        echo "do test" 
