name: Release

on: 
  push:
    tags:
      - v**

jobs:
  build-and-upload:
    name: Build and Upload Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Upload files
        uses: actions/upload-artifact@v2
        with: 
          name: staitc-file
          path: dist/
  release-project:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo ::set-output name=version::$VERSION
          echo "Version $VERSION"
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: staitc-file
      - name: Archive files
        uses: thedoctor0/zip-release@master
        with:
          filename: helloworld.zip          
      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
      - name: Upload asset to Github Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./helloworld.zip
          asset_name: helloworld-${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip